version: 2

sources:
  - name: dev
    database: db
    schema: dev
    tables:
      - name: ohlcv
        columns:
          - name: date
          - name: open
          - name: high
          - name: low
          - name: close
          - name: volume
          - name: weighted_volume
          - name: inserted_at